### ISSUE TITLE
There are a couple of issues with the README.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/bringing-it-all-together#39] opened 2018-12-08 04:37 UTC
Hi. I found a couple of issues with the README.

First, it's missing descriptions of the Dog.create, Dog.find_by_id, and Dog.find_or_create_by class methods. Perhaps this was intentional? The README does say to "start with these methods" (meaning attributes, #create_table, #save, etc.), so maybe the idea was to write those methods first and THEN write the methods I mentioned above.

Another thing about the README is that the last two paragraphs of its description of the tests for #save are completely different from the tests themselves.

Thank you for looking into this!
Sdcrouse

**Comment by sgharms** [comment] 2018-12-11 16:16
@Sdcrouse this looks like a dupe of your other issue. Closing

**Closed as completed by sgharms** 2018-12-11 16:16 UTC
Labels: Curriculum
